sonar.projectKey=backend0
sonar.projectName=Web Nong San Backend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/admin/components/**,src/public/**,src/views/**,src/scripts/**
sonar.exclusions=node_modules/**,coverage/**,allure-results/**,allure-report/**,playwright-report/**,test-results/**,src/pdf/**,src/scripts/**,**/__pycache__/**,**/*.pyc
